version: '3'
services: 
  covid:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "7070:80"
    restart: unless-stopped
    volumes: 
      - ".:/app"
      - "/app/node_modules"
